---
apiVersion: v1
kind: ConfigMap
metadata:
  name: first-chart-configmap-{{.Chart.Version}}
data:
  {{ if eq .Values.env "staging"}}
  port: "8080"
  allowTesting: "true" 
  {{else}}
  port: "3000"
  allowTesting: "false"
  {{end}}